export const SET_LOADING = 'SET_LOADING';
export const UNSET_LOADING = 'UNSET_LOADING';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const RESET_CURRENT_USER = 'RESET_CURRENT_USER';

export const USERLIST_LOAD = 'USERLIST_LOAD';
export const USERLIST_RELOAD = 'USERLIST_RELOAD';
export const USERLIST_UPDATE_PARAMS = 'USERLIST_UPDATE_PARAMS';
